runtime: go
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.9
resources:
  cpu: 2
  memory_gb: 4.0
  disk_size_gb: 5