steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/pong-server:latest', '.' ]
  dir: './'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', "--image-url=us.gcr.io/$PROJECT_ID/appengine/pong-server:latest", "--verbosity=debug"]
timeout: '1600s'
images: [us.gcr.io/$PROJECT_ID/appengine/pong-server:latest]
