steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/pong-server:latest', '.' ]
  images: [gcr.io/$PROJECT_ID/pong-server:latest]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', "./app.yaml"]
timeout: '1600s'
images: ['gcr.io/$PROJECT_ID/pong-server']