steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  id: test
  args: 
  - '-c'
  - |
      ls
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/pong-server:latest', '.' ]
  dir: './'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', "./app.yaml", '--yes']
timeout: '1600s'
images: [gcr.io/$PROJECT_ID/pong-server:latest]
