steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us.gcr.io/$PROJECT_ID/appengine/default:latest', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', "--image-url=us.gcr.io/$PROJECT_ID/appengine/default:latest", "--verbosity=debug"]
timeout: '1600s'
images: [us.gcr.io/$PROJECT_ID/appengine/default:latest]
