steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME/$COMMIT_SHA', '.']
- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME/$COMMIT_SHA']
  id: Push
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'app', 'deploy', '--image-url=gcr.io/$PROJECT_ID/$REPO_NAME/$COMMIT_SHA', '--verbosity=debug']
  id: Deploy
  entrypoint: gcloud
timeout: '1600s'
images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME/$COMMIT_SHA'

options:
 logging: 'CLOUD_LOGGING_ONLY'