steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/pong-server:latest', '.' ]
  dir: './'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', "--image-url=gcr.io/$PROJECT_ID/pong-server:latest", " --verbosity=debug"]
timeout: '1600s'
images: [gcr.io/$PROJECT_ID/pong-server:latest]
